### PR TITLE
Various fixes and improvements

### PR DESCRIPTION
**Pull request by freundTech**
Depends on changes in https://github.com/minecraft-linux/baron/pull/1

### CODE REVIEW

**Comment by ChristopherHX** [comment]
Some changes from this PR are breaking building the x86 (32bit) version of ng.
x86_64 64bit builds fine for me.

**Comment by freundTech** [comment]
I can't reproduce that. I just tried building it with `-DCMAKE_C_FLAGS="-m32" -DCMAKE_CXX_FLAGS="-m32"` and it builds fine.

Maybe it also depends on some changes I did in https://github.com/minecraft-linux/mcpelauncher-client/pull/16? It shouldn't, but it's worth a try if you are not already building against that.
(I'm building https://github.com/minecraft-linux/mcpelauncher-manifest with fake-jni, baron and mcpelauncher-client changed to my forks. Full cmake options are `-DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DBUILD_FAKE_JNI_EXAMPLES=OFF -DBUILD_FAKE_JNI_DEBUG=ON -DBUILD_BARON_DEBUG=ON`)

Can you maybe post the build log?

**Comment by ChristopherHX** [comment]
```
build$ make -j8 mcpelauncher-client
[  2%] Built target eglut
[  5%] Built target linux-gamepad
[  6%] Built target filepicker
[  3%] Built target logger
Cleaning libffi directory...
[  7%] Built target base64
[ 14%] Built target simpleipc
HEAD ist jetzt bei 20562ac Fix for AArch64. Release as 3.2.1.
[ 32%] Built target linker
[ 36%] Built target ffi
[ 40%] Built target gamewindow
[ 41%] Built target mcpelauncher-common
[ 51%] Built target libc-shim
[ 53%] Built target cll-telemetry
[ 54%] Built target file-util
[ 71%] Built target fake-jni
[ 75%] Built target mcpelauncher-core
[ 75%] Built target daemon-client-utils
[ 76%] Building CXX object baron/CMakeFiles/baron.dir/src/impl/interface/native/field.cpp.o
[ 77%] Built target msa-daemon-client
/home/christopher/ng/mcpelauncher-manifest/baron/src/impl/interface/native/field.cpp:65:3: error: use of undeclared identifier 'LOG_GET_FABRICATED_FIELD'
  DEFINE_ARBITRARY_CALLBACKS
  ^
/home/christopher/ng/mcpelauncher-manifest/baron/src/impl/interface/native/field.cpp:52:2: note: expanded from macro 'DEFINE_ARBITRARY_CALLBACKS'
 LOG_GET_FABRICATED_FIELD\
 ^
/home/christopher/ng/mcpelauncher-manifest/baron/src/impl/interface/native/field.cpp:79:3: error: use of undeclared identifier 'LOG_GET_FABRICATED_FIELD'
  DEFINE_ARBITRARY_CALLBACKS
  ^
/home/christopher/ng/mcpelauncher-manifest/baron/src/impl/interface/native/field.cpp:52:2: note: expanded from macro 'DEFINE_ARBITRARY_CALLBACKS'
 LOG_GET_FABRICATED_FIELD\
 ^
2 errors generated.
make[3]: *** [baron/CMakeFiles/baron.dir/build.make:180: baron/CMakeFiles/baron.dir/src/impl/interface/native/field.cpp.o] Fehler 1
make[2]: *** [CMakeFiles/Makefile2:1174: baron/CMakeFiles/baron.dir/all] Fehler 2
make[1]: *** [CMakeFiles/Makefile2:1280: mcpelauncher-client/CMakeFiles/mcpelauncher-client.dir/rule] Fehler 2
make: *** [Makefile:474: mcpelauncher-client] Fehler 2
```
Shure if you want to see it, clang-9.0.0

**Comment by ChristopherHX** [comment]
oh baron, but it's same org
`-DBUILD_BARON_DEBUG=OFF` might be the difference

**Comment by freundTech** [comment]
I pushed a fix to baron. Can you test again?
https://github.com/minecraft-linux/baron/pull/1/commits/0088704e8cd24174b3dbb34b5fbccbfc066f7bf6

**Comment by ChristopherHX** [comment]
_baron works now, for me_

**Comment by ChristopherHX** [comment]
This PR breaks building against xcode11beta (newest xcode), need to check libc++-10 from llvm used in recend dmg builds
```
/Users/christopher/feature-xal/fake-jni/src/jni/native/array.cpp:69:19: error: no member named 'reinterpret_pointer_cast' in namespace 'std'
  auto arr = std::reinterpret_pointer_cast<JArray<void*, true>>(env.resolveReference(jarr));
             ~~~~~^
/Users/christopher/feature-xal/fake-jni/src/jni/native/array.cpp:69:63: error: expected '(' for function-style cast or type construction
  auto arr = std::reinterpret_pointer_cast<JArray<void*, true>>(env.resolveReference(jarr));
```
Usage of c++17 features which only certain library versions ships.

**Comment by freundTech** [comment]
Looks like a static cast is enough here. Only dynamic cast fails at runtime.
I can't test whether it builds in xcode, but static_pointer_cast is available since C++11, so I'd assume this works.

**Pull request merged**
